name: "Pull Request Labeller"
on:
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const pull = await github.rest.pulls.get({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number:  context.issue.number
            });
            const hasReviewLabel = pull.labels?.find(label => label.name === "ğŸ” status: ready for review");
            const hasWipLabel = pull.labels?.find(label => label.name === "âš’ï¸ status: work in progress");
            console.log(pull);
            if (pull.draft && !hasWipLabel) {
              await github.rest.issues.setLabels({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                issue_number: context.issue.number,
                labels: ["âš’ï¸ status: work in progress"]
              })
            } else if (!hasReviewLabel) {
              await github.rest.issues.setLabels({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                issue_number: context.issue.number,
                labels: ["ğŸ” status: ready for review"]
              })
            }
